[tool.ruff]
line-length = 100
target-version = "py310"

[tool.ruff.lint]
# Basic rules: pycodestyle (E), pyflakes (F), import sorting (I)
select = ["E", "F", "I"]
ignore = []

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
