[tool.ruff]
target-version = "py310"
line-length = 100
exclude = [
  ".git",
  ".venv",
  "artifacts",
  "__pycache__",
  ".ruff_cache",
  ".mypy_cache",
  ".pytest_cache",
]

[tool.ruff.lint]
# Basic rule sets: pycodestyle (E), pyflakes (F), import sorting (I)
select = ["E", "F", "I"]
ignore = []

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
